// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EFD003.NpgsqlSample;

public sealed class SampleSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("EFD003.NpgsqlSample.Order", entity =>
        {
            entity.Property<int>("CustomerId");
            entity.HasOne("EFD003.NpgsqlSample.Customer", null)
                .WithMany()
                .HasForeignKey("CustomerId");
        });
    }
}
