// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EFD003.Sample;

internal sealed class SampleContext : DbContext;

internal sealed class CurrentModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("EFD003.Sample.CoveredDependent", entity =>
        {
            entity.HasKey("Id");
            entity.HasIndex("ParentId", "CreatedAt");
            entity.HasOne("EFD003.Sample.Parent", null)
                .WithMany()
                .HasForeignKey("ParentId");
        });

        modelBuilder.Entity("EFD003.Sample.UncoveredDependent", entity =>
        {
            entity.HasKey("Id");
            entity.HasOne("EFD003.Sample.Parent", null)
                .WithMany()
                .HasForeignKey("TenantId", "ParentId");
        });
    }
}

internal sealed class PragmaSuppressedSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("EFD003.Sample.PragmaSuppressed", entity =>
        {
#pragma warning disable EFD003 // Equivalent composite index is managed outside EF migrations.
            entity.HasOne("EFD003.Sample.Parent", null)
                .WithMany()
                .HasForeignKey("ParentId");
#pragma warning restore EFD003
        });
    }
}

[SuppressMessage(
    "Performance",
    "EFD003",
    Justification = "The DBA-managed index is verified during database deployment.")]
internal sealed class AttributeSuppressedSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("EFD003.Sample.AttributeSuppressed", entity =>
        {
            entity.HasOne("EFD003.Sample.Parent", null)
                .WithMany()
                .HasForeignKey("ParentId");
        });
    }
}
