using System.Collections.Immutable;
using System.Reflection;
using EFDoctor.Analyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EFDoctor.Analyzers.Tests;

internal static class AnalyzerTestHarness
{
    private static readonly HashSet<string> OptionalProviderAssemblyNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "Microsoft.EntityFrameworkCore.SqlServer.dll",
        "Npgsql.EntityFrameworkCore.PostgreSQL.dll",
        "Pomelo.EntityFrameworkCore.MySql.dll",
    };

    public static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(
        string source,
        bool includeEntityFramework = true,
        bool includeRelational = false,
        bool includeSqlServer = false,
        bool includeNpgsql = false,
        bool includeMySql = false,
        ReportDiagnostic? configuredSeverity = null,
        DiagnosticAnalyzer? analyzer = null,
        string diagnosticId = SaveChangesInLoopAnalyzer.DiagnosticId)
    {
        var compilation = CreateCompilation(source, includeEntityFramework, includeRelational, includeSqlServer, includeNpgsql, includeMySql, configuredSeverity, diagnosticId);
        var analyzerOptions = new CompilationWithAnalyzersOptions(
            new AnalyzerOptions(ImmutableArray<AdditionalText>.Empty),
            onAnalyzerException: null,
            concurrentAnalysis: true,
            logAnalyzerExecutionTime: false,
            reportSuppressedDiagnostics: false);

        return await compilation
            .WithAnalyzers(ImmutableArray.Create(analyzer ?? new SaveChangesInLoopAnalyzer()), analyzerOptions)
            .GetAnalyzerDiagnosticsAsync();
    }

    public static ImmutableArray<Diagnostic> GetCompilationDiagnostics(
        string source,
        bool includeEntityFramework = true,
        bool includeRelational = false,
        bool includeSqlServer = false,
        bool includeNpgsql = false,
        bool includeMySql = false)
    {
        return CreateCompilation(source, includeEntityFramework, includeRelational, includeSqlServer, includeNpgsql, includeMySql, null, SaveChangesInLoopAnalyzer.DiagnosticId)
            .GetDiagnostics();
    }

    public static string ContextSource(string member, string additionalTypes = "") => $$"""
        using System;
        using System.Collections.Generic;
        using System.Diagnostics.CodeAnalysis;
        using System.Threading;
        using System.Threading.Tasks;
        using Microsoft.EntityFrameworkCore;

        sealed class TestContext : DbContext
        {
        }

        {{additionalTypes}}

        static class Subject
        {
            {{member}}

            private static async IAsyncEnumerable<int> Stream()
            {
                await Task.Yield();
                yield return 1;
            }
        }
        """;

    public static string SnapshotSource(string body, string additionalTypes = "", bool generated = true) => $$"""
        {{(generated ? "// <auto-generated />" : string.Empty)}}
        using System;
        using System.Diagnostics.CodeAnalysis;
        using Microsoft.EntityFrameworkCore;
        using Microsoft.EntityFrameworkCore.Infrastructure;

        sealed class TestContext : DbContext
        {
        }

        {{additionalTypes}}

        sealed class TestSnapshot : ModelSnapshot
        {
            protected override void BuildModel(ModelBuilder modelBuilder)
            {
                {{body}}
            }
        }
        """;

    private static IEnumerable<MetadataReference> TrustedPlatformReferences()
    {
        var paths = ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))?
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            ?? throw new InvalidOperationException("Trusted platform assemblies are unavailable.");
        return paths
            .Where(static path => !OptionalProviderAssemblyNames.Contains(Path.GetFileName(path)))
            .Select(static path => MetadataReference.CreateFromFile(path));
    }

    internal static CSharpCompilation CreateCompilation(
        string source,
        bool includeEntityFramework,
        bool includeRelational,
        bool includeSqlServer,
        bool includeNpgsql,
        bool includeMySql,
        ReportDiagnostic? configuredSeverity,
        string diagnosticId)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(
            source,
            new CSharpParseOptions(LanguageVersion.Preview),
            path: "/tests/Fixture.cs");
        var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            .WithNullableContextOptions(NullableContextOptions.Enable);
        if (configuredSeverity is not null)
        {
            options = options.WithSpecificDiagnosticOptions(
                new Dictionary<string, ReportDiagnostic>
                {
                    [diagnosticId] = configuredSeverity.Value,
                });
        }

        var references = TrustedPlatformReferences().ToList();
        var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (includeEntityFramework)
        {
            AddAssemblyAndDependencies(typeof(DbContext).Assembly, references, visited);
        }

        if (includeRelational || includeSqlServer || includeNpgsql || includeMySql)
        {
            AddAssemblyAndDependencies(typeof(ModelSnapshot).Assembly, references, visited);
        }

        if (includeSqlServer)
        {
            AddAssemblyAndDependencies(typeof(SqlServerDbContextOptionsExtensions).Assembly, references, visited);
        }

        if (includeNpgsql)
        {
            AddAssemblyAndDependencies(typeof(NpgsqlDbContextOptionsBuilderExtensions).Assembly, references, visited);
        }

        if (includeMySql)
        {
            AddAssemblyAndDependencies(typeof(MySqlDbContextOptionsBuilderExtensions).Assembly, references, visited);
        }

        return CSharpCompilation.Create(
            "AnalyzerFixture",
            [syntaxTree],
            references,
            options);
    }

    private static void AddAssemblyAndDependencies(
        Assembly assembly,
        ICollection<MetadataReference> references,
        ISet<string> visited)
    {
        if (assembly.IsDynamic || string.IsNullOrEmpty(assembly.Location) || !visited.Add(assembly.FullName!))
        {
            return;
        }

        references.Add(MetadataReference.CreateFromFile(assembly.Location));
        foreach (var name in assembly.GetReferencedAssemblies())
        {
            try
            {
                AddAssemblyAndDependencies(Assembly.Load(name), references, visited);
            }
            catch (FileNotFoundException)
            {
                // A compilation only needs the dependencies reachable in the local test runtime.
            }
        }
    }
}
