#!/usr/bin/env python3
"""Summarize EFDoctor corpus validation into per-rule and per-project precision.

Reads the run metadata (`<results>/<name>.run.json`) and triage verdicts
(`<results>/triage/<name>.md`) written by run_corpus.py, and writes a Markdown
summary.

Verdicts:
  TP          the finding is correct and worth acting on
  FP          the finding is wrong
  acceptable  the finding correctly identifies the shape, but it is fine in context
  debatable   reasonable people could disagree; excluded from precision
  TODO        not triaged yet

Two precision figures are reported per rule:
  strict precision     TP / (TP + FP + acceptable)            -- how often a finding is worth acting on
  detection precision  (TP + acceptable) / (TP + FP + acceptable) -- how often the rule identified its shape correctly

Usage:
    python3 validation/summarize.py [--results DIR] [--output FILE]
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERDICTS = ("TP", "FP", "acceptable", "debatable", "TODO")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--results", type=Path, default=REPO_ROOT / "validation" / "results")
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "validation" / "SUMMARY.md")
    args = parser.parse_args()

    runs = [json.loads(path.read_text()) for path in sorted(args.results.glob("*.run.json"))]
    by_rule: dict[str, dict[str, int]] = defaultdict(lambda: dict.fromkeys(VERDICTS, 0))
    by_project: dict[str, dict[str, int]] = {}
    for run in runs:
        counts = dict.fromkeys(VERDICTS, 0)
        triage = args.results / "triage" / f"{run['name']}.md"
        for rule, verdict in read_verdicts(triage) if triage.exists() else []:
            by_rule[rule][verdict] += 1
            counts[verdict] += 1
        by_project[run["name"]] = counts

    lines = [
        "# EFDoctor validation summary",
        "",
        "Generated by `validation/summarize.py` from the triage files in `validation/results/triage/`.",
        "",
        "**Strict precision** = TP / (TP + FP + acceptable): how often a finding is worth acting on. "
        "**Detection precision** = (TP + acceptable) / (TP + FP + acceptable): how often the rule identified its shape correctly. "
        "`debatable` findings are excluded; `TODO` findings are not triaged yet.",
        "",
        "## By rule",
        "",
        "| Rule | Findings | TP | FP | acceptable | debatable | TODO | Strict precision | Detection precision |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for rule in sorted(by_rule):
        c = by_rule[rule]
        lines.append(f"| {rule} | {sum(c.values())} | {c['TP']} | {c['FP']} | {c['acceptable']} | {c['debatable']} | {c['TODO']} | {strict(c)} | {detection(c)} |")

    lines += [
        "",
        "## By project",
        "",
        "| Project | Commit | Complete | Findings | TP | FP | acceptable | debatable | TODO | Analysis time |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for run in runs:
        c = by_project[run["name"]]
        complete = "yes" if run.get("complete", run.get("analysisExitCode") in (0, 1)) and run.get("analysisExitCode") in (0, 1) else "**no**"
        lines.append(
            f"| {run['name']} | `{run['commit'][:12]}` | {complete} | {run.get('findingCount', 0)} | "
            f"{c['TP']} | {c['FP']} | {c['acceptable']} | {c['debatable']} | {c['TODO']} | {run.get('analysisSeconds', '–')}s |")

    problems = [run for run in runs if run.get("analysisExitCode") not in (0, 1) or run.get("unrestoredEfProjects") or run.get("analysisWarnings")]
    if problems:
        lines += ["", "## Incomplete runs", ""]
        for run in problems:
            error = run.get("analysisError", "").splitlines()[0][:240] if run.get("analysisError") else ""
            reason = (f"analysis exited with code {run.get('analysisExitCode')}" + (f": {error}" if error else "") if run.get("analysisExitCode") not in (0, 1)
                      else f"{len(run['unrestoredEfProjects'])} EF project(s) not restored" if run.get("unrestoredEfProjects")
                      else f"{len(run['analysisWarnings'])} EF project(s) whose EF Core types did not resolve")
            lines.append(f"- **{run['name']}**: {reason}")

    args.output.write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.output}")


def read_verdicts(path: Path) -> list[tuple[str, str]]:
    verdicts = []
    for block in re.split(r"^## ", path.read_text(), flags=re.M)[1:]:
        rule = block.split(" ", 1)[0]
        match = re.search(r"^- \*\*Verdict:\*\* *(\S*)", block, re.M)
        verdict = match.group(1) if match and match.group(1) in VERDICTS else "TODO"
        verdicts.append((rule, verdict))
    return verdicts


def strict(c: dict[str, int]) -> str:
    denominator = c["TP"] + c["FP"] + c["acceptable"]
    return f"{c['TP'] / denominator:.0%}" if denominator else "–"


def detection(c: dict[str, int]) -> str:
    denominator = c["TP"] + c["FP"] + c["acceptable"]
    return f"{(c['TP'] + c['acceptable']) / denominator:.0%}" if denominator else "–"


if __name__ == "__main__":
    main()
